- init.sh - removed useless checks - add-email-user - write to /etc/shadow without passwd command - renamed user data mount - init.sh - print to stdout

diff --git a/utils/add-email-user b/utils/add-email-user
--- a/utils/add-email-user
+++ b/utils/add-email-user
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 USAGE="Usage: $0 <user>";
 
@@ -12,21 +12,38 @@ fi
 ###################################
 USERNAME=$1;
 LARGEST_ID="$(cat /etc/passwd | sed "/nobody/ s/.*//g" | cut -d ":" -f 3 | sort -n | tail -n 1)"
-UID="$(expr $LARGEST_ID + 1)"
+USER_ID="$(expr $LARGEST_ID + 1)"
 
 echo "info: creating user: $USERNAME"
+
+# Ask for password here, so we can exit before doing anything
+printf "password for user $USERNAME: "
+read -s PASSWORD
+echo
+if [ -z "$PASSWORD" ]; then
+    echo "error: Empty password not allowed. Please try again."
+    exit 1
+fi
+
+printf "confirm password: "
+read -s CONFIRM
+echo
+if [ "$CONFIRM" != "$PASSWORD" ]; then
+    echo "error: Passwords don't match. Please try again."
+    exit 1
+fi
 
 ###################################
 ## USER RECORDS                  ##
 ###################################
 # /etc/passwd
 if ! (grep -q "^$USERNAME:" /etc/passwd); then
-    echo "$USERNAME:x:$UID:$UID::/nonexistent:/bin/sh" >> /etc/passwd
+    echo "$USERNAME:x:$USER_ID:$USER_ID::/nonexistent:/bin/sh" >> /etc/passwd
 fi
 
 # /etc/group - create
 if ! (grep -q "^$USERNAME:" /etc/group); then
-    echo "$USERNAME:x:$UID:" >> /etc/group
+    echo "$USERNAME:x:$USER_ID:" >> /etc/group
 fi
 
 # /etc/group - add to mail group
@@ -39,22 +56,20 @@ if ! (grep -q "^mail:x:.*$USERNAME" /etc/group); then
         INSERT_STRING=",$USERNAME"
     fi
 
-    sed "/mail:x:/ s/$/,$USERNAME/g" /etc/group > $TEMP
+    sed "/mail:x:/ s/$/$INSERT_STRING/g" /etc/group > $TEMP
     cat "$TEMP" > /etc/group
 fi
 
 # /etc/shadow
 if ! (grep -q "^$USERNAME:" /etc/shadow); then
-    ORIGINAL_SHADOW="$(readlink /etc/shadow)"
-    passwd $USERNAME
-    if [ "$?" -ne 0 ]; then
-        echo "error: password creation failed. Run the command again"
-        exit 1
-    fi
+    # Generate salt
+    SALT="$(openssl rand -hex 4)"
+    # Generate the actual password
+    HASH="$(openssl passwd -6 -salt $SALT $PASSWORD)"
+    # Get number of days since epoch
+    DAYS_SINCE_EPOCH="$(( $(date +%s) / 86400 ))"
 
-    # passwd command replaces the symlink, so we must restore it
-    cat /etc/shadow > $ORIGINAL_SHADOW
-    ln -sf $ORIGINAL_SHADOW /etc/shadow
+    echo "$USERNAME:$HASH:$DAYS_SINCE_EPOCH::::::" >> /etc/shadow
 fi
 
 # /etc/gshadow
